[package]
name = "conway-rs"
version = "0.1.0"
authors = ["Jukka-Pekka Virtanen <virtanen@jukk.is>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
term_size = "0.3.1"
minifb = "0.15.0"